- hosts: all
  become: true
  vars:
    path_to_nginx_conf: "./nginx.conf"
    nginx_message: "Hello from Ansible on {{ inventory_hostname }}"
  tasks:
  - name: Install NGINX
    apt:
      name: nginx
      state: latest
      update_cache: true
  - name: Start NGINX Service
    service:
      name: nginx
      state: started
  - name: Add nginx conf
    notify: Restart nginx
    template:
      src: "{{ path_to_nginx_conf }}"
      dest: /etc/nginx/nginx.conf
  - name: Printing host OS
    debug:
        msg: ansible_facts{{ ansible_distribution }}
    when: ansible_facts{{ ansible_distribution }} == ubuntu

  handlers:
  - name: Restart nginx
    service:
      name: nginx
      state: restarted