- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Update apt-get
      apt: upgrade=dist force_apt_get=yes

    - name: Install multiple packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Add Docker official GPG key
      ansible.builtin.command:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        creates: /etc/apt/keyrings

    - name: Set up repository
      ansible.builtin.command:
        cmd: echo \ "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \ $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update apt-get
      apt: upgrade=dist force_apt_get=yes